### ISSUE TITLE
error when running frontend

### ISSUE THREAD

**Issue by buzzblimps** [BUZZ-Blimps/Buzzstation#23]
ran into this error after turning on blimps 
![Screenshot from 2024-09-16 21-37-21](https://github.com/user-attachments/assets/6d587f74-22bb-4e76-bb25-927c66c83afe)

**Comment by buzzblimps** [comment]
buzzstation isn't detecting the blimp when running

**Comment by awilwayco** [comment]
Don't use that link. The Readme states to use 

> http://localhost:8080

where localhost is replaced with the IP address of the device the frontend server is running on.
